name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd projects/skill-exchange
          git remote set-url origin git@github.com:junyou1998/skill-exchange.git
          git reset @^ --hard && git pull
          cd ~/laradock
          docker-compose exec workspace composer install
          docker-compose exec workspace npm install --only=prod
          docker-compose exec workspace npm run dev
          docker-compose exec workspace php artisan config:cache
